python3 scripts/font_converter.py ttf_fonts/Oswald-Light.ttf -s 12
python3 scripts/font_converter.py ttf_fonts/Oswald-Light.ttf -s 16
python3 scripts/font_converter.py ttf_fonts/Oswald-Light.ttf -s 20
python3 scripts/font_converter.py ttf_fonts/Oswald-Light.ttf -s 24
python3 scripts/font_converter.py ttf_fonts/Oswald-Light.ttf -s 36
python3 scripts/font_converter.py ttf_fonts/Oswald-Medium.ttf -s 12
python3 scripts/font_converter.py ttf_fonts/Oswald-Medium.ttf -s 16
python3 scripts/font_converter.py ttf_fonts/Oswald-Medium.ttf -s 20
python3 scripts/font_converter.py ttf_fonts/Oswald-Medium.ttf -s 24
python3 scripts/font_converter.py ttf_fonts/Oswald-Medium.ttf -s 36
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 12
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 16
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 20
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 24
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 36
python3 scripts/font_converter.py ttf_fonts/Oswald-Bold.ttf -s 48
python3 scripts/font_converter.py ttf_fonts/Oswald-Regular.ttf -s 12
python3 scripts/font_converter.py ttf_fonts/Oswald-Regular.ttf -s 16
python3 scripts/font_converter.py ttf_fonts/Oswald-Regular.ttf -s 20
python3 scripts/font_converter.py ttf_fonts/Oswald-Regular.ttf -s 24
python3 scripts/font_converter.py ttf_fonts/Oswald-Regular.ttf -s 36